theme: jekyll-theme-minimal
#theme: jekyll-theme-architect
#theme: jekyll-theme-dinky
#theme: jekyll-theme-slate

#theme: jekyll-theme-cayman
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-minima


title: Loewner world
author: Loewner team
description: Provide a glimpse on the Loewner based results
logo: logo.png
